Repository marcingminski/sqlwatch, pull requests merged in 2021-05, with the labels that each got.

#312 Update README.md
  README.md
Labels: chore

#313 Feature #309. Change to parse job name and replace binary value with …
  SqlWatch.Monitor/Project.SqlWatch.Database/Properties/AssemblyInfo.cs
  SqlWatch.Monitor/Project.SqlWatch.Database/Scripts/Pre-Deployment/SetDacVersion.sql
  SqlWatch.Monitor/Project.SqlWatch.Database/dbo/Functions/ufn_sqlwatch_parse_job_id.sql
  SqlWatch.Monitor/Project.SqlWatch.Database/dbo/Functions/ufn_sqlwatch_parse_job_name.sql
  SqlWatch.Monitor/Project.SqlWatch.Database/dbo/Procedures/usp_sqlwatch_logger_xes_blockers.sql
Labels: enhancement

#314 update documentation to include data source creation via API
  docs/dashboard/grafana.md
Labels: chore, docs

#316 Feature tests
  SqlWatch.Test/Invoke-Tests.ps1
  SqlWatch.Test/Pester.SqlWatch.Test.Checks.ps1
Labels: enhancement

#318 Fixed PK violation caused by genuine duplicate records in the ERRORLO…
  SqlWatch.Monitor/Project.SqlWatch.Database/SQLWATCH.sqlproj
  SqlWatch.Monitor/Project.SqlWatch.Database/Scripts/Pre-Deployment/SetDacVersion.sql
  SqlWatch.Monitor/Project.SqlWatch.Database/dbo/Procedures/usp_sqlwatch_logger_errorlog.sql
  SqlWatch.Monitor/Project.SqlWatch.Database/dbo/Tables/sqlwatch_logger_errorlog.sql
  SqlWatch.Monitor/Project.SqlWatch.Database/dbo/Tables/sqlwatch_meta_errorlog_text.sql
Labels: bug

#319 Added default ERRORLOG keywords that are worth monitoring.
  SqlWatch.Monitor/Project.SqlWatch.Database/SQLWATCH.sqlproj
  SqlWatch.Monitor/Project.SqlWatch.Database/Script.PostDeployment1.sql
  SqlWatch.Monitor/Project.SqlWatch.Database/Scripts/Post-Deployment/Reference-Data/Script.PostDeployment-LoadConfig-DefaultErrorLog.sql
Labels: enhancement

#321 Added separate database for automated tests
  .gitignore
  SqlWatch.Monitor/Project.SqlWatch.Database-Tester/SQLWATCH-TESTER.sqlproj
  SqlWatch.Monitor/Project.SqlWatch.Database-Tester/SQLWATCH-TESTER.sqlproj.user
  SqlWatch.Monitor/Project.SqlWatch.Database-Tester/tester/Tables/sqlwatch_pester_result.sql
  SqlWatch.Monitor/Project.SqlWatch.Database-Tester/tester/tester.sql
  SqlWatch.Monitor/SqlWatch.Monitor.sln
  SqlWatch.Test/Invoke-Tests.ps1
  SqlWatch.Test/Pester.SqlWatch.Test.Checks.ps1
Labels: enhancement

#328 Fixed Bug - Sql Re-Compilations/sec counter. Fix #326
  SqlWatch.Dashboard/Grafana/SQL Instance Overview.json
Labels: bug

#323 Improvements to the test suite
  .gitignore
  SQLWATCH-Build-Release.ps1
  SQLWATCH-Deploy.ps1
  SqlWatch.Monitor/Project.SqlWatch.Database-Tester/SQLWATCH-TESTER.sqlproj
  SqlWatch.Monitor/Project.SqlWatch.Database-Tester/tester/Tables/sqlwatch_blocking_chain.sql
  SqlWatch.Monitor/Project.SqlWatch.Database-Tester/tester/Tables/sqlwatch_long_query.sql
  SqlWatch.Monitor/Project.SqlWatch.Database/SQLWATCH.sqlproj
  SqlWatch.Monitor/Project.SqlWatch.Database/Scripts/Pre-Deployment/SetDacVersion.sql
  SqlWatch.Monitor/Project.SqlWatch.Database/dbo/Functions/ufn_sqlwatch_get_agent_status.sql
  SqlWatch.Monitor/Project.SqlWatch.Database/dbo/Procedures/usp_sqlwatch_config_create_default_agent_jobs.sql
  SqlWatch.Test/Invoke-Tests.ps1
  SqlWatch.Test/Pester.SqlWatch.Test.Checks.p5.ps1
  SqlWatch.Test/Pester.SqlWatch.Test.Checks.ps1
  SqlWatch.Test/ReportUnit.exe
  SqlWatch.Test/Result.SqlWatch.DbaChecks.html
  SqlWatch.Test/Result.SqlWatch.DbaChecks.xml
  SqlWatch.Test/Result.SqlWatch.Test.Checks.html
  SqlWatch.Test/Result.SqlWatch.Test.Checks.xml
  SqlWatch.Test/Run-Tests.p5.ps1
Labels: enhancement

#329 Fixed collation issue in usp_sqlwatch_logger_performance
  SqlWatch.Monitor/Project.SqlWatch.Database/Scripts/Pre-Deployment/SetDacVersion.sql
  SqlWatch.Monitor/Project.SqlWatch.Database/dbo/Procedures/usp_sqlwatch_logger_performance.sql
Labels: bug

#330 Tweaks to the test suite
  SqlWatch.Test/Pester.SqlWatch.Test.Checks.p5.ps1
Labels: enhancement

#331 Add schema validation tests
  SqlWatch.Test/Pester.SqlWatch.Test.Checks.p5.ps1
Labels: enhancement

#332 Add instance name to the Test Suite Name for better visibility on the dashboard
  SqlWatch.Test/Pester.SqlWatch.Test.Checks.p5.ps1
  SqlWatch.Test/Run-Tests.p5.ps1
Labels: enhancement

#333 Fixed `usp_sqlwatch_logger_query_stats` referencing the wrong object
  SqlWatch.Monitor/Project.SqlWatch.Database/dbo/Procedures/usp_sqlwatch_logger_query_stats.sql
Labels: bug

#334 Fixed `usp_sqlwatch_internal_get_query_plans` PK violation
  SqlWatch.Monitor/Project.SqlWatch.Database/Scripts/Pre-Deployment/SetDacVersion.sql
  SqlWatch.Monitor/Project.SqlWatch.Database/dbo/Procedures/usp_sqlwatch_internal_get_query_plans.sql
  SqlWatch.Monitor/Project.SqlWatch.Database/dbo/Procedures/usp_sqlwatch_logger_query_stats.sql
  SqlWatch.Monitor/Project.SqlWatch.Database/dbo/Tables/sqlwatch_meta_query_plan_hash.sql
Labels: bug

#336 Fixed transaction count error in `usp_sqlwatch_logger_whoisactive`
  SqlWatch.Monitor/Project.SqlWatch.Database/dbo/Procedures/usp_sqlwatch_logger_whoisactive.sql
Labels: bug

#339 Update release-drafter.yml
  .github/release-drafter.yml
Labels: chore

#340 Version bump to 4.2
  SqlWatch.Monitor/Project.SqlWatch.Database/Properties/AssemblyInfo.cs
Labels: chore

#345 Improved Performance of XES collectors
  SqlWatch.Monitor/Project.SqlWatch.Database/SQLWATCH.refactorlog
  SqlWatch.Monitor/Project.SqlWatch.Database/Script.PostDeployment1.sql
  SqlWatch.Monitor/Project.SqlWatch.Database/dbo/Functions/ufn_sqlwatch_get_xes_exec_time.sql
  SqlWatch.Monitor/Project.SqlWatch.Database/dbo/Procedures/usp_sqlwatch_internal_get_xes_data.sql
  SqlWatch.Monitor/Project.SqlWatch.Database/dbo/Procedures/usp_sqlwatch_internal_update_xes_query_count.sql
  SqlWatch.Monitor/Project.SqlWatch.Database/dbo/Procedures/usp_sqlwatch_logger_xes_blockers.sql
  SqlWatch.Monitor/Project.SqlWatch.Database/dbo/Procedures/usp_sqlwatch_logger_xes_diagnostics.sql
  SqlWatch.Monitor/Project.SqlWatch.Database/dbo/Procedures/usp_sqlwatch_logger_xes_long_queries.sql
  SqlWatch.Monitor/Project.SqlWatch.Database/dbo/Procedures/usp_sqlwatch_logger_xes_waits.sql
  SqlWatch.Monitor/Project.SqlWatch.Database/dbo/Tables/sqlwatch_logger_xes_iosubsystem.sql
  SqlWatch.Monitor/Project.SqlWatch.Database/dbo/Tables/sqlwatch_logger_xes_query_processing.sql
  SqlWatch.Monitor/Project.SqlWatch.Database/dbo/Tables/sqlwatch_stage_xes_exec_count.sql
Labels: bug, enhancement

#351 Fix casing
  SqlWatch.Monitor/Project.SqlWatch.Database/dbo/Functions/ufn_sqlwatch_parse_xes_event_data.sql
Labels: bug, chore

#352 New tests for `SqlWatchImport.exe`
  .gitignore
  AppVeyor/Build.ps1
  AppVeyor/Test.ps1
  SQLWATCH-Deploy.ps1
  SqlWatch.Test/Pester.SqlWatch.ApplicationLog.ps1
  SqlWatch.Test/Pester.SqlWatch.BasicConfig.ps1
  SqlWatch.Test/Pester.SqlWatch.Blockers.ps1
  SqlWatch.Test/Pester.SqlWatch.BrokerActivation.ps1
  SqlWatch.Test/Pester.SqlWatch.Checks.ps1
  SqlWatch.Test/Pester.SqlWatch.DataRetention.ps1
  SqlWatch.Test/Pester.SqlWatch.Design.ps1
  SqlWatch.Test/Pester.SqlWatch.Errorlog.ps1
  SqlWatch.Test/Pester.SqlWatch.LongQueries.ps1
  SqlWatch.Test/Pester.SqlWatch.ProcedureExecution.ps1
  SqlWatch.Test/Pester.SqlWatch.SqlWatchImport.ps1
  SqlWatch.Test/Pester.SqlWatch.TableContent.ps1
  SqlWatch.Test/Pester.SqlWatch.Test.Checks.p5.ps1
  SqlWatch.Test/Run-Tests.p5.ps1
  SqlWatch.Test/SqlWatch.Test.Functions.psm1
Labels: enhancement

#358 Fixed XES Event Count
  SqlWatch.Monitor/Project.SqlWatch.Database/dbo/Procedures/usp_sqlwatch_internal_get_xes_data.sql
  SqlWatch.Monitor/Project.SqlWatch.Database/dbo/Procedures/usp_sqlwatch_logger_xes_query_problems.sql
  SqlWatch.Monitor/Project.SqlWatch.Database/dbo/Procedures/usp_sqlwatch_logger_xes_waits.sql
Labels: bug

#359 Add ability to capture ERROLOG records based on two keywords. (!)
  SqlWatch.Monitor/Project.SqlWatch.Database/SQLWATCH.refactorlog
  SqlWatch.Monitor/Project.SqlWatch.Database/Scripts/Post-Deployment/Reference-Data/Script.PostDeployment-LoadConfig-DefaultErrorLog.sql
  SqlWatch.Monitor/Project.SqlWatch.Database/dbo/Procedures/usp_sqlwatch_internal_exec_activated.sql
  SqlWatch.Monitor/Project.SqlWatch.Database/dbo/Procedures/usp_sqlwatch_logger_errorlog.sql
  SqlWatch.Monitor/Project.SqlWatch.Database/dbo/Tables/sqlwatch_config_include_errorlog_keywords.sql
  SqlWatch.Monitor/Project.SqlWatch.Database/dbo/Tables/sqlwatch_logger_errorlog.sql
  SqlWatch.Monitor/Project.SqlWatch.Database/dbo/Tables/sqlwatch_meta_errorlog_keyword.sql
  SqlWatch.Monitor/Project.SqlWatch.Database/dbo/Views/vw_sqlwatch_logger_errorlog.sql
Labels: enhancement

#361 XES to log SQLWATCH own performance and problems
  SqlWatch.Monitor/Project.SqlWatch.Database/SQLWATCH.sqlproj
  SqlWatch.Monitor/Project.SqlWatch.Database/dbo/Extended Events/SQLWATCH_health.sql
Labels: enhancement

#362 Reenabled XES to capture problematic queries
  SqlWatch.Monitor/Project.SqlWatch.Database/dbo/Extended Events/SQLWATCH_query_problems.sql
Labels: enhancement

#364 More tweaks to Query Problems XES
  SqlWatch.Monitor/Project.SqlWatch.Database/dbo/Extended Events/SQLWATCH_health.sql
  SqlWatch.Monitor/Project.SqlWatch.Database/dbo/Extended Events/SQLWATCH_query_problems.sql
Labels: enhancement

#365 Fixed Wait Events Grafana Dashboard
  SqlWatch.Dashboard/Grafana/Wait Events.json
  SqlWatch.Monitor/Project.SqlWatch.Database/dbo/Views/vw_sqlwatch_report_fact_xes_wait_events.sql
Labels: bug

#366 Fixed data purge failure introduced in version 4.1
  SqlWatch.Monitor/Project.SqlWatch.Database/dbo/Procedures/usp_sqlwatch_internal_purge_deleted_items.sql
Labels: bug

#367 Brought back carriage return when clearing SQL Text
  SqlWatch.Monitor/Project.SqlWatch.Database/dbo/Functions/ufn_sqlwatch_clean_sql_text.sql
Labels: bug

#368 Fixed expanding checks on central repository
  SqlWatch.Monitor/Project.SqlWatch.Database/dbo/Procedures/usp_sqlwatch_internal_expand_checks.sql
Labels: bug

#369 More Fixes to #354
  SqlWatch.Monitor/Project.SqlWatch.Database/dbo/Procedures/usp_sqlwatch_internal_expand_checks.sql
Labels: bug

#371 Fix Grafana panel reference in alternative charts
  SqlWatch.Dashboard/Grafana/SQL Instance Overview.json
Labels: bug
