Repository marcingminski/sqlwatch, pull requests merged in 2022-09, with the labels that each got.

#447 Fixed minor typo, formatting change in README.md
  README.md
Labels: chore

#450 #403 - Performance Patch
  SqlWatch.Monitor/Project.SqlWatch.Database/dbo/Extended Events/SQLWATCH_health.sql
Labels: bug / bug-fix

#452 Version bump to 4.4
  SqlWatch.Monitor/Project.SqlWatch.Database/Properties/AssemblyInfo.cs
Labels: chore

#454 fix #417
  AppVeyor/Build.ps1
Labels: bug, bugfix

#456 Fix 417
  .gitignore
  AppVeyor/Build.ps1
  SqlWatch.Monitor/Project.SqlWatch.Database/DbVersion.txt
  SqlWatch.Monitor/Project.SqlWatch.Database/SQLWATCH.sqlproj
  SqlWatch.Monitor/Project.SqlWatch.Database/Script.PreDeployment2.sql
  SqlWatch.Monitor/Project.SqlWatch.Database/Scripts/Pre-Deployment/SetDacVersion.sql
  SqlWatch.Monitor/Project.SqlWatch.Database/SetDacVersion.sql
  SqlWatch.Monitor/Project.SqlWatch.Database/WriteDacVersion.targets
Labels: bug

#457 Remove SSIS
  SqlWatch.Monitor/Project.SqlWatch.IntegrationServices/Project.params
  SqlWatch.Monitor/Project.SqlWatch.IntegrationServices/SqlWatch Integration Services.database
  SqlWatch.Monitor/Project.SqlWatch.IntegrationServices/SqlWatch Integration Services.dtproj
  SqlWatch.Monitor/Project.SqlWatch.IntegrationServices/SqlWatch Integration Services.dtproj.user
  SqlWatch.Monitor/Project.SqlWatch.IntegrationServices/control_import.dtsx
  SqlWatch.Monitor/Project.SqlWatch.IntegrationServices/import_remote_data.dtsx
  SqlWatch.Monitor/SqlWatch.Monitor.sln
Labels: chore

#460 Version bump to 4.5
  SqlWatch.Monitor/Project.SqlWatch.Database/DbVersion.txt
Labels: chore
